# fly.toml app configuration file generated for moisson-recup on 2024-09-01T17:28:02-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'moisson-recup'
primary_region = 'yyz'

[build]
  image = 'ghcr.io/pvharmo/moisson-recup:v26-v0.22.20'

[[mounts]]
  source = 'pb_data'
  destination = '/app/pb_data'
  snapshot_retention = 31

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1