name: Check for PocketBase updates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # runs daily at midnight

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PocketBase repository
        uses: actions/checkout@v4
        with: 
          sparse-checkout: |
            pocketbase-version.txt

      - name: Get latest release version
        id: get-latest-version
        run: |
          latest_version=$(curl -s -X GET \
            https://api.github.com/repos/pocketbase/pocketbase/releases/latest \
            | jq -r '.tag_name')
          echo "Latest version: $latest_version"
          echo "latest_version=$latest_version" >> $GITHUB_OUTPUT

      - name: Get current version
        id: get-current-version
        run: |
          current_version=$(cat pocketbase-version.txt)
          echo "Current version: $current_version"
          echo "current_version=$current_version" >> $GITHUB_OUTPUT

      - name: Compare versions
        id: compare-versions
        run: |
          if [ "${{ steps.get-latest-version.outputs.latest_version }}" != "${{ steps.get-current-version.outputs.current_version }}" ]; then
            echo "New version available: ${{ steps.get-latest-version.outputs.latest_version }}"
            echo "new_version_available=true" >> $GITHUB_OUTPUT
          else
            echo "No new version available"
            echo "new_version_available=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger build workflow if new version available
        if: steps.compare-versions.outputs.new_version_available == 'true'
        uses: ./.github/workflows/build-docker-image.yml
        with:
          latest_version: ${{ steps.get-latest-version.outputs.latest_version }}