name: Fly Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Backup the volume and wait to make sure snapshot is complete
        run: flyctl volumes snapshot create ${{ secrets.FLY_VOLUME_ID }} && sleep 20
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_API_TOKEN }}
      - name: Deploy the app
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_API_TOKEN }}
