name: Update and deploy app

on:
  workflow_dispatch:

jobs:
  update:
    uses: ./.github/workflows/check-updates.yml
      
  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: update
    secrets: inherit